server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL_RENDER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema: classpath:schema-postgresql.sql
    initialization-mode: always
